# Generated by Django 5.2.17 on 2026-10-06 09:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


class AdoptUser(migrations.CreateModel):
    """Create on fresh installs; adopt the unchanged auth table on upgrades."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        connection = schema_editor.connection
        tables = connection.introspection.table_names()
        user = to_state.apps.get_model(app_label, self.name)
        if user._meta.db_table not in tables:
            return super().database_forwards(app_label, schema_editor, from_state, to_state)
        with connection.cursor() as cursor:
            columns = {column.name for column in connection.introspection.get_table_description(cursor, 'auth_user')}
        expected = {field.column for field in user._meta.local_fields}
        if columns != expected or not {'auth_user_groups', 'auth_user_user_permissions'} <= set(tables):
            raise RuntimeError('Existing auth_user schema differs; back up and review the upgrade before continuing.')
        for table, expected_columns in [
            ('auth_user_groups', {'id', 'user_id', 'group_id'}),
            ('auth_user_user_permissions', {'id', 'user_id', 'permission_id'}),
        ]:
            with connection.cursor() as cursor:
                columns = {column.name for column in connection.introspection.get_table_description(cursor, table)}
            if columns != expected_columns:
                raise RuntimeError(f'Existing {table} schema differs; review the upgrade before continuing.')

    def database_backwards(self, *args, **kwargs):
        raise IrreversibleError('The adopted user table must not be dropped; restore a database backup to roll back.')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        AdoptUser(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='wearback_users', related_query_name='wearback_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='wearback_users', related_query_name='wearback_user', to='auth.permission')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
