# Generated by Django 5.2.17 on 2026-10-06 09:24

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def normalize_emails(apps, schema_editor):
    User = apps.get_model('main', 'User')
    seen = set()
    for user in User.objects.using(schema_editor.connection.alias).all().iterator():
        email = user.email.strip().lower() if user.email else None
        if email and email in seen:
            raise RuntimeError('Duplicate email addresses exist; resolve them before migrating WearBack accounts.')
        if email:
            seen.add(email)
        User.objects.using(schema_editor.connection.alias).filter(pk=user.pk).update(email=email)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='ui', max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(normalize_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False)), name='wearback_email_unique'),
        ),
        migrations.AddField(
            model_name='ssoidentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ssoidentity',
            constraint=models.UniqueConstraint(fields=('provider', 'subject'), name='sso_subject_unique'),
        ),
        migrations.AddConstraint(
            model_name='ssoidentity',
            constraint=models.UniqueConstraint(fields=('provider', 'user'), name='sso_user_unique'),
        ),
    ]
