# Generated by Django 5.2.17 on 2026-10-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ssoidentity_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthThrottle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
